#!/usr/bin/env bash
#configuring localhost to resolve to 127.0.0.2
# configuring facebook.com to resolve to 8.8.8.8

# Backup the original hosts file
cp /etc/hosts ~/hosts.new

# modify localhost
echo "127.0.0.2	   localhost" | tee -a /etc/hosts
echo "8.8.8.8	   facebook.com" | tee -a /etc/hosts

